Task Id
CS2103JAN2017-T11-B4/main pull request #106
Opened 2017-03-19 10:07 UTC by KellyLi

Adding task id (time of task creation in ms), still need to write tests

2017-03-19 12:32 UTC, evanyeung requested changes
Looks good! Marking that I looked at it but requesting changes till tests are fixed.

2017-03-19 12:32 UTC, evanyeung commented on src/main/java/seedu/task/model/util/SampleDataUtil.java
> +                new Task(new Description("Alex Yeoh"), null, null, new UniqueTagList("friends"), null),
It looks like you've made the `id` field non-nullable in the constructor (which seems right to me). Will this cause tests to fail?

2017-03-19 12:32 UTC, evanyeung commented on src/test/java/seedu/task/testutil/TestUtil.java
> +                new Task(new Description("Ali Muster"), null, null, new UniqueTagList(), null),
Same as above about asserting null id in the constructor.

2017-03-19 12:32 UTC, evanyeung commented on src/main/java/seedu/task/model/task/Task.java
> +    private final TaskId id;
Nice, thanks!

2017-03-20 09:23 UTC, closed without merging

2017-03-20 09:24 UTC, KellyLi commented
Closing and reopening on another branch with fixed tests