search through tags
CS2103JAN2017-T11-B4/main pull request #160
Opened 2017-03-28 07:23 UTC by JoshuaChing

https://github.com/CS2103JAN2017-T11-B4/main/issues/131

- include searching through tags
- not case sensitive
- change searching description to use contains rather than equals

2017-03-28 10:04 UTC, KellyLi commented on src/main/java/seedu/task/commons/util/StringUtil.java
> +            if (wordInSentence.toLowerCase().contains(preppedWord.toLowerCase())) return true;
This means that search isn't case sensitive, right? The user guide would need to be updated. : )

2017-03-28 10:19 UTC, JoshuaChing commented on src/main/java/seedu/task/commons/util/StringUtil.java
> +            if (wordInSentence.toLowerCase().contains(preppedWord.toLowerCase())) return true;
Wasn't the search always not case sensitive?

2017-03-28 14:59 UTC, KellyLi commented on src/main/java/seedu/task/commons/util/StringUtil.java
> +            if (wordInSentence.toLowerCase().contains(preppedWord.toLowerCase())) return true;
Search used to be case sensitive

2017-03-28 18:46 UTC, JoshuaChing commented on src/main/java/seedu/task/commons/util/StringUtil.java
> +            if (wordInSentence.toLowerCase().contains(preppedWord.toLowerCase())) return true;
wordInSentence.equalsIgnoreCase(preppedWord) <-- that ignores case

either way I've updated the docs 👍

2017-03-29 03:39 UTC, KellyLi requested changes

2017-03-29 03:39 UTC, KellyLi commented on src/test/java/seedu/task/logic/LogicManagerTest.java
> +        Task p3 = helper.generatePersonWithName("KE Y");
Should this be generateTaskWithDescription?

2017-03-29 03:39 UTC, KellyLi commented on src/test/java/seedu/task/logic/LogicManagerTest.java
> +        Task t1 = helper.generateTaskWithNameAndTags("a", "bcd", "efg", "jj");
Should this be generateTaskWithDescriptionAndTags?

2017-03-29 07:06 UTC, JoshuaChing commented on src/test/java/seedu/task/logic/LogicManagerTest.java
> +        Task p3 = helper.generatePersonWithName("KE Y");
fixed

2017-03-29 07:24 UTC, merged

2017-03-29 07:25 UTC, JoshuaChing commented
Not sure why CI is failing, DateParserTest are unrelated to my changes. Ignoring and merging.